export const FETCH_EVENT_LIST_DATA = "FETCH_EVENT_LIST_DATA";
export const FETCH_EVENT_LIST_KEYWORD = "FETCH_EVENT_LIST_KEYWORD";
export const FETCH_EVENT_LIST_PAGE = "FETCH_EVENT_LIST_PAGE";
export const FETCH_EVENT_LIST_LOADING = "FETCH_EVENT_LIST_LOADING";
export const FETCH_EVENT_RETRIEVE_DATA = "FETCH_EVENT_RETRIEVE_DATA";
export const FETCH_EVENT_RETRIEVE_LOADING = "FETCH_EVENT_RETRIEVE_LOADING";
export const SEARCH_EVENTS = "SEARCH_EVENTS";
export const SEARCH_EVENTS_LOADING = "SEARCH_EVENTS_LOADING";
